### ISSUE TITLE
Support for "every" for ScheduledResource

### ISSUE THREAD

**Issue by sebt3** [NCCloud/mayfly#46]
Hi,

First, mayfly is a very usefull tool, thanks a lot.
The ScheduledResource is nice, but I'ld love for a recurring version of it. Primary use-case would be to trigger a PipelineRun (tektoncd). So being able to do something like :
```
apiVersion: cloud.namecheap.com/v1alpha1
kind: ScheduledResource
metadata:
  name: dayly-cleanup
  namespace: admin
spec:
  every: 24h
  content: |
    apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      annotations:
        mayfly.cloud.namecheap.com/expire: 336h
      generateName: dayly-cleanup-
      namespace: admin
    spec:
      pipelineRef:
        name: dayly-cleanup
      taskRunTemplate:
        serviceAccountName: default
      timeouts:
        pipeline: 1h0m0s
      workspaces:
      - name: ssh
        secret:
          items:
          - key: known_hosts
            path: known_hosts
          - key: ssh-privatekey
            path: id_rsa
          - key: ssh-publickey
            path: id_rsa.pub
          secretName: ssh-credentials
```
would be very awesome. Note that i'm using `generateName` instead of a `name` in the created object so k8s generate a id after last dash.

EDIT: a crontab-style option might also be liked
