### ISSUE TITLE
ScheduledResource does not get deleted after expiration duration/date

### ISSUE THREAD

**Issue by RafaelBroseghini** [NCCloud/mayfly#79]
Correct me if I'm wrong but in the example below: 

after 5s -> create Secret -> after 10s -> Delete ScheduledResource -> after 15s -> Delete Secret

```yaml
apiVersion: cloud.namecheap.com/v1alpha1
kind: ScheduledResource
metadata:
  name: combination-example
  annotations:
    mayfly.cloud.namecheap.com/expire: 10s
spec:
  in: "5s"
  content: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: combination-example
      namespace: default
      annotations:
        mayfly.cloud.namecheap.com/expire: 10s
    data:
      .secret-file: dmFsdWUtMg0KDQo=
```

I noticed the ScheduledResource is never getting cleaned up. Should mayfly not delete the ScheduledResource CR after 10s?

```
NAME                  IN    AGE    CONDITION
combination-example   5s    3m3s   Created
```
